### ISSUE TITLE
Using Spring Cloud Vault with appid / userid authentication

### ISSUE THREAD

**Issue by avirkar** [mp911de/spring-cloud-vault-config-samples#7]
We have a requirement where in we need to use spring cloud vault with appid / userid authentication. We are going to have the SSL disabled. With the examples that you provided for spring cloud or spring core. I was unable to figure this out. Could you help me with some examples where I can achieve this

**Comment by mp911de** [comment]
Please use StackOverflow for general questions.

Checkout the [reference documentation](http://cloud.spring.io/spring-cloud-vault/single/spring-cloud-vault.html#_client_side_usage) for setting `spring.cloud.vault.scheme`.
