### ISSUE TITLE
certificate renewal without application restart

### ISSUE THREAD

**Issue by tkautenburger** [mp911de/spring-cloud-vault-config-samples#9]
I used your PKI example for certificate distribution with Vault. As I understand, the applications only renew their key and certificate when they get restarted. What would be the best approach to renew key and certificate during application runtime?

**Comment by mp911de** [comment]
Certificate renewal depends on your use-case. For client-usage, you would need to reconfigure your client with a new keystore. That typically can happen without service disruption.

For servers, I think you need to re-start your server component. I'm not sure to which extent this is possible without a short interruption in the service as I'm not so much involved into Tomcat's `Http11NioProtocol`. Check out the [Spring Boot docs](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html#howto-enable-multiple-connectors-in-tomcat) on SSL configuration.
